apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - My First Group:
      - UniFi:
          icon:  unifi.png
          href:  https://unifi
          widget:
              type:  unifi
              url:  https://192.168.0.1
              username: "homepage"
              password: "HomepagePassword1#"

    - My Second Group:
        - My Second Service:
            href: http://localhost/
            description: Homepage is the best

    - My Third Group:
        - My Third Service:
            href: http://localhost/
            description: Homepage is 😎
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - datetime:
      text_size: xl
      locale: en
      format:
        hour12: false
        dateStyle: short
        timeStyle: short
    - search:
        provider: google
        showSearchSuggestions: true
        target: _blank
  docker.yaml: ""
